// Generated by CoffeeScript 2.3.1
(function() {
  'use strict';
  var CND, TAP, alert, badge, debug, echo, eq, help, info, jr, log, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'INTERGRID/TESTS';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  TAP = require('tap');

  eq = CND.equals;

  jr = JSON.stringify;

  //-----------------------------------------------------------------------------------------------------------
  TAP.test("demo", function(T) {
    T.ok(eq(1, 1));
    //.........................................................................................................
    return T.end();
  });

}).call(this);

//# sourceMappingURL=main.js.map
